server:
  port: 8082

spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: ${MONGO_URI_ACTIVITY}
      database: ${MONGO_DATABASE_ACTIVITY}

eureka:
  client:
    eureka-url:
      defaultZone: ${EUREKA_URL}

base:
  url:
    user-service: http://USER-SERVICE