version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD_USER}
      POSTGRES_DB: fitness_user_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - fitness_network

  mongodb:
    container_name: mongo_container
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - fitness_network

  rabbitmq:
    container_name: rabbit_container
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    restart: unless-stopped
    networks:
      - fitness_network

volumes:
  pg_data:
  mongo_data:

networks:
  fitness_network:
    driver: bridge
    name: fitness_network
