server:
  port: 8083

spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE}

eureka:
  client:
    eureka-url:
      defaultZone: ${EUREKA_URL}