spring:
  datasource:
    url: ${DB_URL_USER}
    username: ${DB_USERNAME_USER}
    password: ${DB_PASSWORD_USER}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    eureka-url:
      defaultZone: ${EUREKA_URL}

server:
  port: 8081
